### ISSUE TITLE
Rename `_pronamic_review_product_id` to `_pronamic_review_post_id`?

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-reviews-ratings#2]
Is `_pronamic_review_post_id` perhaps more general and clear? For reviews for services, companies, etc., the term 'product' may be less obvious. And the term `post_id` makes it immediately clear that a post ID is stored in it.

**Comment by rvdsteege** [comment]
`_pronamic_review_post_id` sounds like the post ID of a review, which it is not. It's the post ID of the item being reviewed. Maybe something more like `_pronamic_review_object_post_id` or `_pronamic_review_origin_post_id`?

**Comment by remcotolsma** [comment]
`_pronamic_review_object_post_id` seems fine to me too, has some similarities with https://developer.wordpress.org/reference/functions/get_queried_object/. If we ever want to support user reviews we can `_pronamic_review_object_user_id` or for terms `_pronamic_review_object_term_id`.

https://schema.org/itemReviewed
